/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilIndexRouteImport } from './routes/profil.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as ProfilModifierRouteImport } from './routes/profil.modifier'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'
import { Route as JobsPostulationsRouteImport } from './routes/jobs.postulations'
import { Route as JobsCreerRouteImport } from './routes/jobs.creer'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'

const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilModifierRoute = ProfilModifierRouteImport.update({
  id: '/profil/modifier',
  path: '/profil/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsPostulationsRoute = JobsPostulationsRouteImport.update({
  id: '/jobs/postulations',
  path: '/jobs/postulations',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsCreerRoute = JobsCreerRouteImport.update({
  id: '/jobs/creer',
  path: '/jobs/creer',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/creer': typeof JobsCreerRoute
  '/jobs/postulations': typeof JobsPostulationsRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/jobs/': typeof JobsIndexRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/creer': typeof JobsCreerRoute
  '/jobs/postulations': typeof JobsPostulationsRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/jobs': typeof JobsIndexRoute
  '/profil': typeof ProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/creer': typeof JobsCreerRoute
  '/jobs/postulations': typeof JobsPostulationsRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/jobs/': typeof JobsIndexRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/jobs/$id'
    | '/jobs/creer'
    | '/jobs/postulations'
    | '/profil/$id'
    | '/profil/modifier'
    | '/jobs/'
    | '/profil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/jobs/$id'
    | '/jobs/creer'
    | '/jobs/postulations'
    | '/profil/$id'
    | '/profil/modifier'
    | '/jobs'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/jobs/$id'
    | '/jobs/creer'
    | '/jobs/postulations'
    | '/profil/$id'
    | '/profil/modifier'
    | '/jobs/'
    | '/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  JobsIdRoute: typeof JobsIdRoute
  JobsCreerRoute: typeof JobsCreerRoute
  JobsPostulationsRoute: typeof JobsPostulationsRoute
  ProfilIdRoute: typeof ProfilIdRoute
  ProfilModifierRoute: typeof ProfilModifierRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/modifier': {
      id: '/profil/modifier'
      path: '/profil/modifier'
      fullPath: '/profil/modifier'
      preLoaderRoute: typeof ProfilModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/postulations': {
      id: '/jobs/postulations'
      path: '/jobs/postulations'
      fullPath: '/jobs/postulations'
      preLoaderRoute: typeof JobsPostulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/creer': {
      id: '/jobs/creer'
      path: '/jobs/creer'
      fullPath: '/jobs/creer'
      preLoaderRoute: typeof JobsCreerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  JobsIdRoute: JobsIdRoute,
  JobsCreerRoute: JobsCreerRoute,
  JobsPostulationsRoute: JobsPostulationsRoute,
  ProfilIdRoute: ProfilIdRoute,
  ProfilModifierRoute: ProfilModifierRoute,
  JobsIndexRoute: JobsIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
