/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilIndexRouteImport } from './routes/profil.index'
import { Route as ProfilModifierRouteImport } from './routes/profil.modifier'
import { Route as ProfilIdRouteImport } from './routes/profil.$id'

const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilModifierRoute = ProfilModifierRouteImport.update({
  id: '/profil/modifier',
  path: '/profil/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/profil': typeof ProfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/profil/$id': typeof ProfilIdRoute
  '/profil/modifier': typeof ProfilModifierRoute
  '/profil/': typeof ProfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/profil/$id'
    | '/profil/modifier'
    | '/profil/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connexion' | '/profil/$id' | '/profil/modifier' | '/profil'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/profil/$id'
    | '/profil/modifier'
    | '/profil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  ProfilIdRoute: typeof ProfilIdRoute
  ProfilModifierRoute: typeof ProfilModifierRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/modifier': {
      id: '/profil/modifier'
      path: '/profil/modifier'
      fullPath: '/profil/modifier'
      preLoaderRoute: typeof ProfilModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$id': {
      id: '/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  ProfilIdRoute: ProfilIdRoute,
  ProfilModifierRoute: ProfilModifierRoute,
  ProfilIndexRoute: ProfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
